import { imageUrls } from "../../images/ImageUrl";
const products = [
    {
        id: 1,
        imgUrl: imageUrls[1],
        name: "NIKE AIR FORCE 1 - DONUT STYLE",
        price: 2700000,
        brand: "nike",
    },
    {
        id: 2,
        imgUrl: imageUrls[2],
        name: "NIKE AIR FORCE 1 - DONUT STYLE",
        price: 2700000,
        brand: "nike",
    },
    {
        id: 3,
        imgUrl: imageUrls[3],
        name: "NIKE AIR FORCE 1 PURPLE SNAKE",
        price: 3700000,
        brand: "nike",
    },
    {
        id: 4,
        imgUrl: imageUrls[4],
        name: "NIKE AIR FORCE 1 - BLUE BUTTERFLIES",
        price: 3200000,
        brand: "nike",
    },
    {
        id: 5,
        imgUrl: imageUrls[5],
        name: "NIKE AIR FORCE 1 - ORANGE BUTTERFLIES",
        price: 2899000,
        brand: "nike",
    },
    {
        id: 6,
        imgUrl: imageUrls[6],
        name: "NIKE AIR FORCE 1 COLORFUL SKETCH",
        price: 2600000,
        brand: "nike",
    },
    {
        id: 7,
        imgUrl: imageUrls[7],
        name: "NIKE AIR FORCE 1 SKY BLUE SKETCH",
        price: 2500000,
        brand: "nike",
    },
    {
        id: 8,
        imgUrl: imageUrls[8],
        name: "NIKE AIR FORCE 1 RED-ORANGE SKETCH",
        price: 2700000,
        brand: "nike",
    },
    {
        id: 9,
        imgUrl: imageUrls[9],
        name: "NIKE AIR FORCE 1 COLORFUL SKETCH 2.0",
        price: 2700000,
        brand: "nike",
    },
    {
        id: 10,
        imgUrl: imageUrls[10],
        name: "NIKE AIR FORCE 1",
        price: 3100000,
        brand: "nike",
    },
    {
        id: 11,
        imgUrl: imageUrls[11],
        name: "NIKE AIR FORCE 1 - PINK BUTTERFLIES",
        price: 2799000,
        brand: "nike",
    },
    {
        id: 12,
        imgUrl: imageUrls[12],
        name: "NIKE AIR FORCE 1 SPLASH",
        price: 2750000,
        brand: "nike",
    },
    {
        id: 13,
        imgUrl: imageUrls[13],
        name: "NIKE AIR FORCE 1 BLUE 'N WHITE",
        price: 2800000,
        brand: "nike",
    },
    {
        id: 14,
        imgUrl: imageUrls[14],
        name: "NIKE AIR FORCE 1 RED 'N WHITE",
        price: 2800000,
        brand: "nike",
    },
    {
        id: 15,
        imgUrl: imageUrls[15],
        name: "NIKE AIR FORCE 1 PURPLE SKETCH",
        price: 2500000,
        brand: "nike",
    },
    {
        id: 16,
        imgUrl: imageUrls[16],
        name: "NIKE AIR FORCE 1 SKETCH - CYAN SWOOSH",
        price: 2900000,
        brand: "nike",
    },
    {
        id: 17,
        imgUrl: imageUrls[17],
        name: "NIKE AIR FORCE 1 - GREY SKETCHES",
        price: 3000000,
        brand: "nike",
    },
    {
        id: 18,
        imgUrl: imageUrls[18],
        name: "NIKE AIR FORCE 1 SPLATTERED PURPLE/VIOLET",
        price: 2600000,
        brand: "nike",
    },
    {
        id: 19,
        imgUrl: imageUrls[19],
        name: "NIKE AIR FORCE 1 PLAYBOY BUNNY REFLECTIVE",
        price: 2400000,
        brand: "nike",
    },
    {
        id: 20,
        imgUrl: imageUrls[20],
        name: "NIKE AIR FORCE 1 JOKER - WHY SO SERIOUS?",
        price: 2750000,
        brand: "nike",
    },
    {
        id: 21,
        imgUrl: imageUrls[21],
        name: "NIKE AIR FORCE 1 SPLASH SPLASH",
        price: 2300000,
        brand: "nike",
    },
    {
        id: 22,
        imgUrl: imageUrls[22],
        name: "NIKE AIR FORCE 1 - WHITE X YELLOW",
        price: 2500000,
        brand: "nike",
    },
    {
        id: 23,
        imgUrl: imageUrls[23],
        name: "NIKE AIR FORCE 1 TOM & JERRY",
        price: 4000000,
        brand: "nike",
    },
    {
        id: 24,
        imgUrl: imageUrls[24],
        name: "NIKE AIR FORCE 1 BLUE LIGHTNING",
        price: 2750000,
        brand: "nike",
    },
    {
        id: 25,
        imgUrl: imageUrls[25],
        name: "NIKE AIR FORCE 1 BLUE SKETCH",
        price: 3000000,
        brand: "nike",
    },
    {
        id: 26,
        imgUrl: imageUrls[26],
        name: "NIKE AIR FORCE 1 LIGHTNING",
        price: 2250000,
        brand: "nike",
    },
    {
        id: 27,
        imgUrl: imageUrls[27],
        name: "NIKE AIR FORCE 1 DRIPS",
        price: 2150000,
        brand: "nike",
    },
    {
        id: 28,
        imgUrl: imageUrls[28],
        name: "NIKE AIR FORCE 1 DRIPS",
        price: 2250000,
        brand: "nike",
    },
    {
        id: 29,
        imgUrl: imageUrls[29],
        name: "NIKE AIR FORCE 1 LOW DIAMONDS - BROWN",
        price: 3200000,
        brand: "nike",
    },
    {
        id: 30,
        imgUrl: imageUrls[30],
        name: "NIKE AIR MAX 90 DIAMOND - WHITE",
        price: 6000000,
        brand: "nike",
    },
    {
        id: 31,
        imgUrl: imageUrls[31],
        name: "NIKE AIR FORCE 1 - SPONGEBOBS",
        price: 6290000,
        brand: "nike",
    },
    {
        id: 32,
        imgUrl: imageUrls[32],
        name: "AIR FORCE 1 GLITCH",
        price: 5890000,
        brand: "nike",
    },
    {
        id: 33,
        imgUrl: imageUrls[33],
        name: "EMRE VONK - CREATE YOUR OWN - SLAM!",
        price: 5500000,
        brand: "nike",
    },
    {
        id: 34,
        imgUrl: imageUrls[34],
        name: "NIKE AIR MAX 90 DIAMOND - WHITE",
        price: 6000000,
        brand: "nike",
    },
    {
        id: 35,
        imgUrl: imageUrls[35],
        name: "NIKE AIR FORCE 1 BLACK SKETCH",
        price: 3000000,
        brand: "nike",
    },
    {
        id: 36,
        imgUrl: imageUrls[36],
        name: "NIKE AIR MAX 270 REACT DIAMOND - BLACK/WHITE",
        price: 4890000,
        brand: "nike",
    },
    {
        id: 37,
        imgUrl: imageUrls[37],
        name: "NIKE AIR FORCE 1 '07 LOW - ZWART HEREN",
        price: 3190000,
        brand: "nike",
    },
    {
        id: 38,
        imgUrl: imageUrls[38],
        name: "NIKE AIR MAX 90 DIAMOND - BLACK",
        price: 4800000,
        brand: "nike",
    },
    {
        id: 39,
        imgUrl: imageUrls[39],
        name: "NIKE AIR MAX 270 REACT DIAMOND - BLACK",
        price: 4500000,
        brand: "nike",
    },
    {
        id: 40,
        imgUrl: imageUrls[40],
        name: "NIKE AIR MAX 90 DIAMOND - BLACK",
        price: 4790000,
        brand: "nike",
    },
    {
        id: 41,
        imgUrl: imageUrls[41],
        name: "NIKE AIR FORCE 1 BLACK GOLD SPLATTERED",
        price: 3200000,
        brand: "nike",
    },
    {
        id: 42,
        imgUrl: imageUrls[42],
        name: "NIKE AIR FORCE 1 07 LOW - GRIJS HEREN",
        price: 2200000,
        brand: "nike",
    },
    {
        id: 43,
        imgUrl: imageUrls[43],
        name: "NIKE AIR FORCE 1 '07 LOW - WIT",
        price: 2200000,
        brand: "nike",
    },

    {
        id: 44,
        imgUrl: imageUrls[44],
        name: "ADIDAS STAN SMITH - DONUT DRIP - GOLD",
        price: 2500000,
        brand: "adidas",
    },
    {
        id: 45,
        imgUrl: imageUrls[45],
        name: "ADIDAS SUPERSTAR - PURPLE GLITTER",
        price: 2800000,
        brand: "adidas",
    },
    {
        id: 46,
        imgUrl: imageUrls[46],
        name: "ADIDAS SUPERSTAR - PINK GLITTER",
        price: 2700000,
        brand: "adidas",
    },
    {
        id: 47,
        imgUrl: imageUrls[47],
        name: "ADIDAS SUPERSTAR - GOLD GLITTER",
        price: 3200000,
        brand: "adidas",
    },
    {
        id: 48,
        imgUrl: imageUrls[48],
        name: "ADIDAS SUPERSTAR - LIGHT BLUE GLITTER",
        price: 2899000,
        brand: "adidas",
    },
    {
        id: 49,
        imgUrl: imageUrls[49],
        name: "ADIDAS SUPERSTAR - STARLIGHT BLUE GLITTER",
        price: 2600000,
        brand: "adidas",
    },
    {
        id: 50,
        imgUrl: imageUrls[50],
        name: "ADIDAS SUPERSTAR - SILVER GLITTER",
        price: 2500000,
        brand: "adidas",
    },
    {
        id: 51,
        imgUrl: imageUrls[51],
        name: "ADIDAS SUPERSTAR - RED GLITTER",
        price: 2700000,
        brand: "adidas",
    },
    {
        id: 52,
        imgUrl: imageUrls[52],
        name: "ADIDAS STAN SMITH - DONUT DRIP - GREEN",
        price: 2700000,
        brand: "adidas",
    },
    {
        id: 53,
        imgUrl: imageUrls[53],
        name: "ADIDAS STAN SMITH - KMO",
        price: 3100000,
        brand: "adidas",
    },
    {
        id: 54,
        imgUrl: imageUrls[54],
        name: "ADIDAS STAN SMITH - KEITH HARRING",
        price: 2799000,
        brand: "adidas",
    },
    {
        id: 55,
        imgUrl: imageUrls[55],
        name: "ADIDAS STAN SMITH - JOKER",
        price: 2750000,
        brand: "adidas",
    },

    {
        id: 56,
        imgUrl: imageUrls[56],
        name: "ADIDAS STAN SMITH - HEARTS",
        price: 2800000,
        brand: "adidas",
    },
    {
        id: 57,
        imgUrl: imageUrls[57],
        name: "ADIDAS STAN SMITH - FORTNITE",
        price: 2800000,
        brand: "adidas",
    },
    {
        id: 58,
        imgUrl: imageUrls[58],
        name: "BABY - ADIDAS STAN SMITH - MINNIE MOUSE & PLUTO",
        price: 2500000,
        brand: "adidas",
    },
    {
        id: 59,
        imgUrl: imageUrls[59],
        name: "BABY - ADIDAS STAN SMITH - MINNIE MOUSE",
        price: 2900000,
        brand: "adidas",
    },
    {
        id: 60,
        imgUrl: imageUrls[60],
        name: "BABY - ADIDAS STAN SMITH - PLUTO",
        price: 3000000,
        brand: "adidas",
    },
    {
        id: 61,
        imgUrl: imageUrls[61],
        name: "Adidas Superstar Diamond Skull",
        price: 2600000,
        brand: "adidas",
    },
    {
        id: 62,
        imgUrl: imageUrls[62],
        name: "BABY - ADIDAS STAN SMITH - CHARMANDER",
        price: 2400000,
        brand: "adidas",
    },
    {
        id: 63,
        imgUrl: imageUrls[63],
        name: "Adidas Superstar Split",
        price: 2750000,
        brand: "adidas",
    },
    {
        id: 64,
        imgUrl: imageUrls[64],
        name: "Adidas Superstar Purple Rain",
        price: 2300000,
        brand: "adidas",
    },
    {
        id: 65,
        imgUrl: imageUrls[65],
        name: "Adidas Superstar Indigo Bleached",
        price: 2500000,
        brand: "adidas",
    },
    {
        id: 66,
        imgUrl: imageUrls[66],
        name: "Adidas Superstar Pop Eyes",
        price: 4000000,
        brand: "adidas",
    },
    {
        id: 67,
        imgUrl: imageUrls[67],
        name: "Adidas Superstar Black Star",
        price: 2750000,
        brand: "adidas",
    },
    {
        id: 68,
        imgUrl: imageUrls[68],
        name: "Adidas Superstar Blue Boost",
        price: 3000000,
        brand: "adidas",
    },
    {
        id: 69,
        imgUrl: imageUrls[69],
        name: "Adidas Superstar London Silver",
        price: 2250000,
        brand: "adidas",
    },
    {
        id: 70,
        imgUrl: imageUrls[70],
        name: "Adidas Superstar Fix",
        price: 2150000,
        brand: "adidas",
    },
    {
        id: 71,
        imgUrl: imageUrls[71],
        name: "Adidas Superstar Magic",
        price: 2250000,
        brand: "adidas",
    },
    {
        id: 72,
        imgUrl: imageUrls[72],
        name: "Adidas Superstar Brooklyn",
        price: 3200000,
        brand: "adidas",
    },

    {
        id: 73,
        imgUrl: imageUrls[73],
        name: "VANS OLD SKOOL - DONUT DRIP",
        price: 2200000,
        brand: "vans",
    },
    {
        id: 74,
        imgUrl: imageUrls[74],
        name: "VANS OLD SKOOL - DONUT DRIP",
        price: 3000000,
        brand: "vans",
    },
    {
        id: 75,
        imgUrl: imageUrls[75],
        name: "VANS OLD SKOOL DIAMONDS - CHESS",
        price: 2900000,
        brand: "vans",
    },
    {
        id: 76,
        imgUrl: imageUrls[76],
        name: "VANS OLD SKOOL DIAMONDS - GREY",
        price: 3800000,
        brand: "vans",
    },
    {
        id: 77,
        imgUrl: imageUrls[77],
        name: "VANS OLD SKOOL DIAMONDS - LEOPARD",
        price: 7000000,
        brand: "vans",
    },
    {
        id: 78,
        imgUrl: imageUrls[78],
        name: "VANS OLD SKOOL DIAMONDS - PURPLE",
        price: 6900000,
        brand: "vans",
    },
    {
        id: 79,
        imgUrl: imageUrls[79],
        name: "VANS OLD SKOOL X BABE SHARK TEETH'S",
        price: 3200000,
        brand: "vans",
    },
    {
        id: 80,
        imgUrl: imageUrls[80],
        name: "Vans Customs x Disney 100 Multi Character Sk8-Hi Shoe",
        price: 5000000,
        brand: "vans",
    },
    {
        id: 81,
        imgUrl: imageUrls[81],
        name: "Disney X Vans Customs Mickey Old Skool Shoe",
        price: 4000000,
        brand: "vans",
    },
    {
        id: 82,
        imgUrl: imageUrls[82],
        name: "VANS SLIP-ON CUSTOM CULTURE 2018",
        price: 2000000,
        brand: "vans",
    },
];

export default products;
