const vietnamCities = [
    { city: "Ha Noi", deli_cost: 40000 },
    { city: "Ho Chi Minh City", deli_cost: 20000 },
    { city: "Da Nang", deli_cost: 40000 },
    { city: "Hai Phong", deli_cost: 40000 },
    { city: "Can Tho", deli_cost: 40000 },
    

    // "An Giang",
    // "Bac Kan",
    // "Bac Ninh",
    // "Ba Ria Vung Tau",
    // "Ben Tre",
    // "Binh Dinh",
    // "Binh Duong",
    // "Binh Phuoc",
    // "Binh Thuan",
    // "Ca Mau",
    // "Cao Bang",
    // "Dien Bien",
    // "Dong Nai",
    // "Dong Thap",
    // "Gia Lai",
    // "Ha Giang",
    // "Ha Nam",
    // "Ha Tinh",
    // "Hung Yen",
    // "Khanh Hoa",
    // "Kien Giang",
    // "Lai Chau",
    // "Lam Dong",
    // "Lao Cai",
    // "Long An",
    // "Nam Dinh",
    // "Nghe An",
    // "Ninh Binh",
    // "Ninh Thuan",
    // "Phu Tho",
    // "Phu Yen",
    // "Quang Binh",
    // "Quang Nam",
    // "Quang Ngai",
    // "Quang Ninh",
    // "Quang Tri",
    // "Soc Trang",
    // "Son La",
    // "Tay Ninh",
    // "Thap Muoi",
    // "Thai Binh",
    // "Thanh Hoa",
    // "Thua Thien Hue",
    // "Tien Giang",
    // "Tra Vinh",
    // "Tuyen Quang",
    // "Vinh Long",
    // "Yen Bai",
];

export default vietnamCities
